// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Settings.h"
#include "ui_Mainui.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_88054402);    // assets/back-arrow-50.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_up_arrow_png);    // assets/up_arrow.png
LV_IMG_DECLARE(ui_img_down_arrow_png);    // assets/down_arrow.png

// FONTS
LV_FONT_DECLARE(ui_font_Euro15);
LV_FONT_DECLARE(ui_font_euro20);
LV_FONT_DECLARE(ui_font_Euro40);
LV_FONT_DECLARE(ui_font_Euro60);
LV_FONT_DECLARE(ui_font_Euro80);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
