// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Mainui = NULL;
lv_obj_t * ui_Speed = NULL;
lv_obj_t * ui_Speedlabel = NULL;
lv_obj_t * ui_Watts = NULL;
lv_obj_t * ui_Watt_Label = NULL;
lv_obj_t * ui_Info = NULL;
lv_obj_t * ui_Temps = NULL;
lv_obj_t * ui_Motor_Temp = NULL;
lv_obj_t * ui_Controller_temp = NULL;
lv_obj_t * ui_settings1 = NULL;
lv_obj_t * ui_Odometer = NULL;
// event funtions
void ui_event_settings1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Mainui_screen_init(void)
{
    ui_Mainui = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Mainui, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Mainui, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Mainui, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed = lv_arc_create(ui_Mainui);
    lv_obj_set_width(ui_Speed, 200);
    lv_obj_set_height(ui_Speed, 200);
    lv_obj_set_x(ui_Speed, -120);
    lv_obj_set_y(ui_Speed, 0);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_Speed, 0);

    lv_obj_set_style_arc_color(ui_Speed, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Speed, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Speedlabel = lv_label_create(ui_Speed);
    lv_obj_set_width(ui_Speedlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Speedlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speedlabel, "00");
    lv_obj_set_style_text_color(ui_Speedlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speedlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speedlabel, &ui_font_Euro60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Watts = lv_arc_create(ui_Mainui);
    lv_obj_set_width(ui_Watts, 200);
    lv_obj_set_height(ui_Watts, 200);
    lv_obj_set_x(ui_Watts, 120);
    lv_obj_set_y(ui_Watts, 0);
    lv_obj_set_align(ui_Watts, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Watts, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_Watts, 0);
    lv_arc_set_mode(ui_Watts, LV_ARC_MODE_REVERSE);

    lv_obj_set_style_arc_color(ui_Watts, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Watts, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Watt_Label = lv_label_create(ui_Watts);
    lv_obj_set_width(ui_Watt_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Watt_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Watt_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Watt_Label, "0000");
    lv_obj_set_style_text_color(ui_Watt_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Watt_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Watt_Label, &ui_font_Euro40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info = lv_obj_create(ui_Mainui);
    lv_obj_remove_style_all(ui_Info);
    lv_obj_set_height(ui_Info, 50);
    lv_obj_set_width(ui_Info, lv_pct(100));
    lv_obj_set_align(ui_Info, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temps = lv_obj_create(ui_Info);
    lv_obj_remove_style_all(ui_Temps);
    lv_obj_set_height(ui_Temps, lv_pct(55));
    lv_obj_set_width(ui_Temps, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Temps, 20);
    lv_obj_set_y(ui_Temps, 0);
    lv_obj_set_align(ui_Temps, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Temps, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Temps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temps, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motor_Temp = lv_label_create(ui_Temps);
    lv_obj_set_width(ui_Motor_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motor_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Motor_Temp, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Motor_Temp, "00.0c");

    ui_Controller_temp = lv_label_create(ui_Temps);
    lv_obj_set_width(ui_Controller_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Controller_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Controller_temp, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Controller_temp, "00.0c");

    ui_settings1 = lv_image_create(ui_Info);
    lv_image_set_src(ui_settings1, &ui_img_settings_png);
    lv_obj_set_width(ui_settings1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_settings1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_settings1, 200);
    lv_obj_set_style_image_recolor(ui_settings1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_settings1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Odometer = lv_label_create(ui_Mainui);
    lv_obj_set_width(ui_Odometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Odometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Odometer, 0);
    lv_obj_set_y(ui_Odometer, -40);
    lv_obj_set_align(ui_Odometer, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Odometer, "000000");
    lv_obj_set_style_text_color(ui_Odometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Odometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Odometer, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_settings1, ui_event_settings1, LV_EVENT_ALL, NULL);

}

void ui_Mainui_screen_destroy(void)
{
    if(ui_Mainui) lv_obj_del(ui_Mainui);

    // NULL screen variables
    ui_Mainui = NULL;
    ui_Speed = NULL;
    ui_Speedlabel = NULL;
    ui_Watts = NULL;
    ui_Watt_Label = NULL;
    ui_Info = NULL;
    ui_Temps = NULL;
    ui_Motor_Temp = NULL;
    ui_Controller_temp = NULL;
    ui_settings1 = NULL;
    ui_Odometer = NULL;

}
