// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAINUI_H
#define UI_MAINUI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Mainui
extern void ui_Mainui_screen_init(void);
extern void ui_Mainui_screen_destroy(void);
extern lv_obj_t * ui_Mainui;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_Speedlabel;
extern lv_obj_t * ui_Watts;
extern lv_obj_t * ui_Watt_Label;
extern lv_obj_t * ui_Info;
extern lv_obj_t * ui_Temps;
extern lv_obj_t * ui_Motor_Temp;
extern lv_obj_t * ui_Controller_temp;
extern void ui_event_settings1(lv_event_t * e);
extern lv_obj_t * ui_settings1;
extern lv_obj_t * ui_Odometer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

