// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: square project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_TabPage4 = NULL;
lv_obj_t * ui_TabPage5 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1);
    lv_tabview_set_tab_bar_size(ui_TabView1, 50);
    lv_obj_set_width(ui_TabView1, lv_pct(100));
    lv_obj_set_height(ui_TabView1, lv_pct(100));
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Title 1");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Title 2");

    ui_Label1 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "text");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Title 3");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "Title 4");

    ui_TabPage5 = lv_tabview_add_tab(ui_TabView1, "Title 5");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_TabPage2 = NULL;
    ui_Label1 = NULL;
    ui_TabPage3 = NULL;
    ui_TabPage4 = NULL;
    ui_TabPage5 = NULL;

}
