// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Live_battery_info;
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_battery_percent;
extern lv_obj_t * ui_Amps;
extern lv_obj_t * ui_Battery_Connect_info;
extern lv_obj_t * ui_Cell_info;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Controller_info;
extern lv_obj_t * ui_Control_label;
extern lv_obj_t * ui_data_container;
extern lv_obj_t * ui_Mode_container;
extern lv_obj_t * ui_Power_modes;
extern lv_obj_t * ui_Mode_settings;
extern lv_obj_t * ui_Eco_Mode;
extern lv_obj_t * ui_EcoSpeed;
extern lv_obj_t * ui_EcoPower;
extern lv_obj_t * ui_TabPage3;
extern void ui_event_back_button(lv_event_t * e);
extern lv_obj_t * ui_back_button;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

