// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_battery_bridge.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_Live_battery_info = NULL;
lv_obj_t * ui_Voltage = NULL;
lv_obj_t * ui_battery_percent = NULL;
lv_obj_t * ui_Amps = NULL;
lv_obj_t * ui_Battery_Connect_info = NULL;
lv_obj_t * ui_Cell_info = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Controller_info = NULL;
lv_obj_t * ui_Control_label = NULL;
lv_obj_t * ui_data_container = NULL;
lv_obj_t * ui_Mode_container = NULL;
lv_obj_t * ui_Power_modes = NULL;
lv_obj_t * ui_Mode_settings = NULL;
lv_obj_t * ui_Eco_Mode = NULL;
lv_obj_t * ui_EcoSpeed = NULL;
lv_obj_t * ui_EcoPower = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_back_button = NULL;
// event funtions
void ui_event_back_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Mainui, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Mainui_screen_init);
    }
}

static void ui_spinbox_inc_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED || event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_obj_t * sb = (lv_obj_t *)lv_event_get_user_data(e);
        if (sb) lv_spinbox_increment(sb);
    }
}

static void ui_spinbox_dec_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED || event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_obj_t * sb = (lv_obj_t *)lv_event_get_user_data(e);
        if (sb) lv_spinbox_decrement(sb);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Settings);
    lv_tabview_set_tab_bar_size(ui_TabView1, 30);
    lv_obj_set_height(ui_TabView1, 280);
    lv_obj_set_width(ui_TabView1, lv_pct(100));
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, 20);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_dir(ui_TabView1, LV_DIR_NONE);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Battery");
    lv_obj_remove_flag(ui_TabPage1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Live_battery_info = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Live_battery_info);
    lv_obj_set_height(ui_Live_battery_info, 30);
    lv_obj_set_width(ui_Live_battery_info, lv_pct(100));
    lv_obj_set_x(ui_Live_battery_info, 0);
    lv_obj_set_y(ui_Live_battery_info, -7);
    lv_obj_set_align(ui_Live_battery_info, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Live_battery_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Live_battery_info, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Live_battery_info, lv_color_hex(0xABABAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Live_battery_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Live_battery_info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Live_battery_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Voltage = lv_label_create(ui_Live_battery_info);
    lv_obj_set_width(ui_Voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Voltage, 20);
    lv_obj_set_y(ui_Voltage, 0);
    lv_obj_set_align(ui_Voltage, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Voltage, "84.4v");

    ui_battery_percent = lv_label_create(ui_Live_battery_info);
    lv_obj_set_width(ui_battery_percent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery_percent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_battery_percent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battery_percent, "100%");

    ui_Amps = lv_label_create(ui_Live_battery_info);
    lv_obj_set_width(ui_Amps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Amps, -20);
    lv_obj_set_y(ui_Amps, 0);
    lv_obj_set_align(ui_Amps, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Amps, "0a");

    lv_obj_t * ui_Battery_Cell_container = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Battery_Cell_container);
    lv_obj_set_width(ui_Battery_Cell_container, lv_pct(100));
    lv_obj_set_height(ui_Battery_Cell_container, 180);
    lv_obj_set_x(ui_Battery_Cell_container, 0);
    lv_obj_set_y(ui_Battery_Cell_container, 40);
    lv_obj_set_align(ui_Battery_Cell_container, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Battery_Cell_container, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                    LV_OBJ_FLAG_SCROLL_MOMENTUM);
    lv_obj_set_scroll_dir(ui_Battery_Cell_container, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(ui_Battery_Cell_container, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_add_flag(ui_Battery_Cell_container, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_Battery_Cell_container, LV_OBJ_FLAG_SCROLL_CHAIN);

    lv_obj_t * ui_Battery_Cell_content = lv_obj_create(ui_Battery_Cell_container);
    lv_obj_remove_style_all(ui_Battery_Cell_content);
    lv_obj_set_width(ui_Battery_Cell_content, lv_pct(100));
    lv_obj_set_height(ui_Battery_Cell_content, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Battery_Cell_content, 0);
    lv_obj_set_y(ui_Battery_Cell_content, 0);
    lv_obj_set_align(ui_Battery_Cell_content, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Battery_Cell_content, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_Battery_Cell_content, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_Battery_Cell_content, LV_OBJ_FLAG_SCROLL_ELASTIC);
    lv_obj_add_flag(ui_Battery_Cell_content, LV_OBJ_FLAG_SCROLL_MOMENTUM);
    lv_obj_add_flag(ui_Battery_Cell_content, LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_scroll_dir(ui_Battery_Cell_content, LV_DIR_VER);

    ui_Battery_Connect_info = lv_obj_create(ui_Battery_Cell_content);
    lv_obj_remove_style_all(ui_Battery_Connect_info);
    lv_obj_set_height(ui_Battery_Connect_info, 280);
    lv_obj_set_width(ui_Battery_Connect_info, lv_pct(49));
    lv_obj_set_x(ui_Battery_Connect_info, 0);
    lv_obj_set_y(ui_Battery_Connect_info, 0);
    lv_obj_set_align(ui_Battery_Connect_info, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Battery_Connect_info, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_Battery_Connect_info, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_Battery_Connect_info, LV_OBJ_FLAG_SCROLL_ELASTIC);
    lv_obj_add_flag(ui_Battery_Connect_info, LV_OBJ_FLAG_SCROLL_MOMENTUM);
    lv_obj_add_flag(ui_Battery_Connect_info, LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_scroll_dir(ui_Battery_Connect_info, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Battery_Connect_info, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Connect_info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Connect_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Connect_info, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cell_info = lv_obj_create(ui_Battery_Cell_content);
    lv_obj_remove_style_all(ui_Cell_info);
    lv_obj_set_height(ui_Cell_info, LV_SIZE_CONTENT);
    lv_obj_set_width(ui_Cell_info, lv_pct(49));
    lv_obj_set_x(ui_Cell_info, 0);
    lv_obj_set_y(ui_Cell_info, 0);
    lv_obj_set_align(ui_Cell_info, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Cell_info, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_Cell_info, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_Cell_info, LV_OBJ_FLAG_SCROLL_ELASTIC);
    lv_obj_add_flag(ui_Cell_info, LV_OBJ_FLAG_SCROLL_MOMENTUM);
    lv_obj_add_flag(ui_Cell_info, LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_scroll_dir(ui_Cell_info, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Cell_info, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Cell_info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Cell_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Cell_info, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery_bridge_init();

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Controller");
    lv_obj_remove_flag(ui_TabPage2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TabPage2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TabPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabPage2, &ui_font_euro20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Controller_info = lv_obj_create(ui_TabPage2);
    lv_obj_remove_style_all(ui_Controller_info);
    lv_obj_set_width(ui_Controller_info, lv_pct(49));
    lv_obj_set_height(ui_Controller_info, lv_pct(100));
    lv_obj_set_align(ui_Controller_info, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Controller_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Controller_info, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Control_label = lv_label_create(ui_Controller_info);
    lv_obj_set_width(ui_Control_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Control_label, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Control_label, "Controller Info");

    ui_data_container = lv_obj_create(ui_Controller_info);
    lv_obj_remove_style_all(ui_data_container);
    lv_obj_set_width(ui_data_container, lv_pct(100));
    lv_obj_set_height(ui_data_container, lv_pct(80));
    lv_obj_set_x(ui_data_container, 0);
    lv_obj_set_y(ui_data_container, 5);
    lv_obj_set_align(ui_data_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_data_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_flex_flow(ui_data_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_data_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_data_container, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_data_container, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scroll_dir(ui_data_container, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_data_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_session = lv_obj_create(ui_data_container);
    lv_obj_remove_style_all(vesc_session);
    lv_obj_set_width(vesc_session, lv_pct(100));
    lv_obj_set_height(vesc_session, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(vesc_session, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(vesc_session, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(vesc_session, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_sess_title = lv_label_create(vesc_session);
    lv_obj_set_width(vesc_sess_title, lv_pct(100));
    lv_label_set_text(vesc_sess_title, "Session Peaks");
    lv_obj_set_style_text_font(vesc_sess_title, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_sess_title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_sess_trip = lv_label_create(vesc_session);
    lv_obj_set_width(vesc_sess_trip, lv_pct(100));
    lv_label_set_text(vesc_sess_trip, "Trip: -");
    lv_obj_set_style_text_font(vesc_sess_trip, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_sess_trip, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_sess_speed = lv_label_create(vesc_session);
    lv_obj_set_width(vesc_sess_speed, lv_pct(100));
    lv_label_set_text(vesc_sess_speed, "Peak Speed: -");
    lv_obj_set_style_text_font(vesc_sess_speed, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_sess_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_sess_watts = lv_label_create(vesc_session);
    lv_obj_set_width(vesc_sess_watts, lv_pct(100));
    lv_label_set_text(vesc_sess_watts, "Peak Watts: -");
    lv_obj_set_style_text_font(vesc_sess_watts, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_sess_watts, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_sess_motor = lv_label_create(vesc_session);
    lv_obj_set_width(vesc_sess_motor, lv_pct(100));
    lv_label_set_text(vesc_sess_motor, "Peak Motor: -");
    lv_obj_set_style_text_font(vesc_sess_motor, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_sess_motor, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_sess_ctrl = lv_label_create(vesc_session);
    lv_obj_set_width(vesc_sess_ctrl, lv_pct(100));
    lv_label_set_text(vesc_sess_ctrl, "Peak Ctrl: -");
    lv_obj_set_style_text_font(vesc_sess_ctrl, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_sess_ctrl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_sess_whpk = lv_label_create(vesc_session);
    lv_obj_set_width(vesc_sess_whpk, lv_pct(100));
    lv_label_set_text(vesc_sess_whpk, "Wh/km: -");
    lv_obj_set_style_text_font(vesc_sess_whpk, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_sess_whpk, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist = lv_obj_create(ui_data_container);
    lv_obj_remove_style_all(vesc_hist);
    lv_obj_set_width(vesc_hist, lv_pct(100));
    lv_obj_set_height(vesc_hist, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(vesc_hist, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(vesc_hist, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(vesc_hist, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist_title = lv_label_create(vesc_hist);
    lv_obj_set_width(vesc_hist_title, lv_pct(100));
    lv_label_set_text(vesc_hist_title, "Historical Peaks");
    lv_obj_set_style_text_font(vesc_hist_title, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hist_title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(vesc_hist_title, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(vesc_hist_title, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(vesc_hist_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(vesc_hist_title, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist_odo = lv_label_create(vesc_hist);
    lv_obj_set_width(vesc_hist_odo, lv_pct(100));
    lv_label_set_text(vesc_hist_odo, "Odo: -");
    lv_obj_set_style_text_font(vesc_hist_odo, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hist_odo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist_speed = lv_label_create(vesc_hist);
    lv_obj_set_width(vesc_hist_speed, lv_pct(100));
    lv_label_set_text(vesc_hist_speed, "Peak Speed: -");
    lv_obj_set_style_text_font(vesc_hist_speed, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hist_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist_watts = lv_label_create(vesc_hist);
    lv_obj_set_width(vesc_hist_watts, lv_pct(100));
    lv_label_set_text(vesc_hist_watts, "Peak Watts: -");
    lv_obj_set_style_text_font(vesc_hist_watts, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hist_watts, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist_motor = lv_label_create(vesc_hist);
    lv_obj_set_width(vesc_hist_motor, lv_pct(100));
    lv_label_set_text(vesc_hist_motor, "Peak Motor: -");
    lv_obj_set_style_text_font(vesc_hist_motor, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hist_motor, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist_ctrl = lv_label_create(vesc_hist);
    lv_obj_set_width(vesc_hist_ctrl, lv_pct(100));
    lv_label_set_text(vesc_hist_ctrl, "Peak Ctrl: -");
    lv_obj_set_style_text_font(vesc_hist_ctrl, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hist_ctrl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hist_whpk = lv_label_create(vesc_hist);
    lv_obj_set_width(vesc_hist_whpk, lv_pct(100));
    lv_label_set_text(vesc_hist_whpk, "Wh/km: -");
    lv_obj_set_style_text_font(vesc_hist_whpk, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hist_whpk, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_fw = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_fw, lv_pct(100));
    lv_label_set_long_mode(vesc_fw, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_fw, "FW: (waiting)");
    lv_obj_set_style_text_font(vesc_fw, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_fw, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(vesc_fw, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(vesc_fw, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(vesc_fw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(vesc_fw, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_hw = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_hw, lv_pct(100));
    lv_label_set_long_mode(vesc_hw, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_hw, "HW: (waiting)");
    lv_obj_set_style_text_font(vesc_hw, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_hw, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_ble = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_ble, lv_pct(100));
    lv_label_set_long_mode(vesc_ble, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_ble, "BLE: -");
    lv_obj_set_style_text_font(vesc_ble, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_ble, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_poles = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_poles, lv_pct(100));
    lv_label_set_long_mode(vesc_poles, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_poles, "Poles: -");
    lv_obj_set_style_text_font(vesc_poles, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_poles, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_gear = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_gear, lv_pct(100));
    lv_label_set_long_mode(vesc_gear, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_gear, "Gear: -");
    lv_obj_set_style_text_font(vesc_gear, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_gear, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_wheel = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_wheel, lv_pct(100));
    lv_label_set_long_mode(vesc_wheel, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_wheel, "Wheel: -");
    lv_obj_set_style_text_font(vesc_wheel, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_wheel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_vin = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_vin, lv_pct(100));
    lv_label_set_long_mode(vesc_vin, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_vin, "Vin: -");
    lv_obj_set_style_text_font(vesc_vin, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_vin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_imax = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_imax, lv_pct(100));
    lv_label_set_long_mode(vesc_imax, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_imax, "Imax: -");
    lv_obj_set_style_text_font(vesc_imax, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_imax, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_fet_end = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_fet_end, lv_pct(100));
    lv_label_set_long_mode(vesc_fet_end, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_fet_end, "FET end: -");
    lv_obj_set_style_text_font(vesc_fet_end, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_fet_end, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * vesc_motor_end = lv_label_create(ui_data_container);
    lv_obj_set_width(vesc_motor_end, lv_pct(100));
    lv_label_set_long_mode(vesc_motor_end, LV_LABEL_LONG_WRAP);
    lv_label_set_text(vesc_motor_end, "Motor end: -");
    lv_obj_set_style_text_font(vesc_motor_end, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(vesc_motor_end, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mode_container = lv_obj_create(ui_TabPage2);
    lv_obj_remove_style_all(ui_Mode_container);
    lv_obj_set_width(ui_Mode_container, lv_pct(49));
    lv_obj_set_height(ui_Mode_container, lv_pct(100));
    lv_obj_set_align(ui_Mode_container, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Mode_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Power_modes = lv_label_create(ui_Mode_container);
    lv_obj_set_width(ui_Power_modes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Power_modes, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Power_modes, "Power Modes");
    lv_obj_set_style_text_color(ui_Power_modes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Power_modes, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mode_settings = lv_obj_create(ui_Mode_container);
    lv_obj_remove_style_all(ui_Mode_settings);
    lv_obj_set_width(ui_Mode_settings, lv_pct(100));
    lv_obj_set_height(ui_Mode_settings, lv_pct(90));
    lv_obj_set_x(ui_Mode_settings, 0);
    lv_obj_set_y(ui_Mode_settings, 10);
    lv_obj_set_align(ui_Mode_settings, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Mode_settings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Mode_settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_Mode_settings, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_Mode_settings, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scroll_dir(ui_Mode_settings, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_Mode_settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Eco_Mode = lv_obj_create(ui_Mode_settings);
    lv_obj_set_height(ui_Eco_Mode, 140);
    lv_obj_set_width(ui_Eco_Mode, lv_pct(100));
    lv_obj_set_align(ui_Eco_Mode, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Eco_Mode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Eco_Mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Eco_Mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Eco_Mode, lv_color_hex(0x1BFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Eco_Mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Eco_Mode, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Eco_Mode, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Eco_Mode, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Eco_Mode, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * eco_label = lv_label_create(ui_Eco_Mode);
    lv_obj_set_width(eco_label, lv_pct(100));
    lv_label_set_text(eco_label, "Eco Mode Settings");
    lv_obj_set_style_text_font(eco_label, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(eco_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(eco_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EcoSpeed = lv_spinbox_create(ui_Eco_Mode);
    lv_obj_set_width(ui_EcoSpeed, 100);
    lv_obj_set_height(ui_EcoSpeed, 42);
    lv_obj_set_align(ui_EcoSpeed, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(ui_EcoSpeed, 0);
    lv_obj_set_y(ui_EcoSpeed, 30);
    lv_obj_remove_flag(ui_EcoSpeed, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                   LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_spinbox_set_digit_format(ui_EcoSpeed, 2, 0);
    lv_spinbox_set_range(ui_EcoSpeed, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_EcoSpeed, 1 - 1);
    lv_obj_set_style_text_color(ui_EcoSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EcoSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EcoSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_EcoSpeed, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EcoSpeed, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EcoSpeed, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EcoSpeed, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_EcoPower = lv_spinbox_create(ui_Eco_Mode);
    lv_obj_set_width(ui_EcoPower, 100);
    lv_obj_set_height(ui_EcoPower, 42);
    lv_obj_set_align(ui_EcoPower, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_EcoPower, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                   LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_spinbox_set_digit_format(ui_EcoPower, 4, 0);
    lv_spinbox_set_range(ui_EcoPower, 100, 9999);
    lv_spinbox_set_cursor_pos(ui_EcoPower, 3 - 1);
    lv_obj_set_style_text_color(ui_EcoPower, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EcoPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EcoPower, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_EcoPower, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EcoPower, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EcoPower, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EcoPower, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_t * eco_power_up = lv_image_create(ui_Eco_Mode);
    lv_image_set_src(eco_power_up, &ui_img_up_arrow_png);
    lv_obj_set_size(eco_power_up, 40, 40);
    lv_obj_set_x(eco_power_up, 0);
    lv_obj_set_y(eco_power_up, 30);
    lv_obj_set_align(eco_power_up, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(eco_power_up, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(eco_power_up, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(eco_power_up, ui_spinbox_inc_cb, LV_EVENT_ALL, ui_EcoSpeed);
    lv_obj_set_style_radius(eco_power_up, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(eco_power_up, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(eco_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(eco_power_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(eco_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(eco_power_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(eco_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(eco_power_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(eco_power_up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(eco_power_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * eco_power_dn = lv_image_create(ui_Eco_Mode);
    lv_image_set_src(eco_power_dn, &ui_img_down_arrow_png);
    lv_obj_set_size(eco_power_dn, 40, 40);
    lv_obj_set_x(eco_power_dn, -50);
    lv_obj_set_y(eco_power_dn, 30);
    lv_obj_set_align(eco_power_dn, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(eco_power_dn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(eco_power_dn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(eco_power_dn, ui_spinbox_dec_cb, LV_EVENT_ALL, ui_EcoSpeed);
    lv_obj_set_style_radius(eco_power_dn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(eco_power_dn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(eco_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(eco_power_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(eco_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(eco_power_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(eco_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(eco_power_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(eco_power_dn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(eco_power_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * eco_speed_dn = lv_image_create(ui_Eco_Mode);
    lv_image_set_src(eco_speed_dn, &ui_img_down_arrow_png);
    lv_obj_set_size(eco_speed_dn, 40, 40);
    lv_obj_set_x(eco_speed_dn, -50);
    lv_obj_set_y(eco_speed_dn, 0);
    lv_obj_set_align(eco_speed_dn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(eco_speed_dn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(eco_speed_dn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(eco_speed_dn, ui_spinbox_dec_cb, LV_EVENT_ALL, ui_EcoPower);
    lv_obj_set_style_radius(eco_speed_dn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(eco_speed_dn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(eco_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(eco_speed_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(eco_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(eco_speed_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(eco_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(eco_speed_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(eco_speed_dn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(eco_speed_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * eco_speed_up = lv_image_create(ui_Eco_Mode);
    lv_image_set_src(eco_speed_up, &ui_img_up_arrow_png);
    lv_obj_set_size(eco_speed_up, 40, 40);
    lv_obj_set_align(eco_speed_up, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(eco_speed_up, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(eco_speed_up, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(eco_speed_up, ui_spinbox_inc_cb, LV_EVENT_ALL, ui_EcoPower);
    lv_obj_set_style_radius(eco_speed_up, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(eco_speed_up, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(eco_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(eco_speed_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(eco_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(eco_speed_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(eco_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(eco_speed_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(eco_speed_up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(eco_speed_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * sport_panel = lv_obj_create(ui_Mode_settings);
    lv_obj_set_height(sport_panel, 140);
    lv_obj_set_width(sport_panel, lv_pct(100));
    lv_obj_set_align(sport_panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(sport_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(sport_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sport_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sport_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sport_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(sport_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(sport_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(sport_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(sport_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * sport_label = lv_label_create(sport_panel);
    lv_obj_set_width(sport_label, lv_pct(100));
    lv_label_set_text(sport_label, "Sport Mode Settings");
    lv_obj_set_style_text_font(sport_label, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(sport_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(sport_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * sport_speed = lv_spinbox_create(sport_panel);
    lv_obj_set_width(sport_speed, 100);
    lv_obj_set_height(sport_speed, 42);
    lv_obj_set_align(sport_speed, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(sport_speed, 0);
    lv_obj_set_y(sport_speed, 30);
    lv_obj_remove_flag(sport_speed, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                   LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_spinbox_set_digit_format(sport_speed, 2, 0);
    lv_spinbox_set_range(sport_speed, 0, 9999);
    lv_spinbox_set_cursor_pos(sport_speed, 1 - 1);
    lv_obj_set_style_text_color(sport_speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(sport_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(sport_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(sport_speed, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sport_speed, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(sport_speed, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(sport_speed, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_t * sport_power = lv_spinbox_create(sport_panel);
    lv_obj_set_width(sport_power, 100);
    lv_obj_set_height(sport_power, 42);
    lv_obj_set_align(sport_power, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(sport_power, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                   LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_spinbox_set_digit_format(sport_power, 4, 0);
    lv_spinbox_set_range(sport_power, 100, 9999);
    lv_spinbox_set_cursor_pos(sport_power, 3 - 1);
    lv_obj_set_style_text_color(sport_power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(sport_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(sport_power, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(sport_power, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sport_power, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(sport_power, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(sport_power, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_t * sport_power_up = lv_image_create(sport_panel);
    lv_image_set_src(sport_power_up, &ui_img_up_arrow_png);
    lv_obj_set_size(sport_power_up, 40, 40);
    lv_obj_set_x(sport_power_up, 0);
    lv_obj_set_y(sport_power_up, 30);
    lv_obj_set_align(sport_power_up, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(sport_power_up, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(sport_power_up, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(sport_power_up, ui_spinbox_inc_cb, LV_EVENT_ALL, sport_speed);
    lv_obj_set_style_radius(sport_power_up, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sport_power_up, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sport_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sport_power_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(sport_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(sport_power_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(sport_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(sport_power_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(sport_power_up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(sport_power_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * sport_power_dn = lv_image_create(sport_panel);
    lv_image_set_src(sport_power_dn, &ui_img_down_arrow_png);
    lv_obj_set_size(sport_power_dn, 40, 40);
    lv_obj_set_x(sport_power_dn, -50);
    lv_obj_set_y(sport_power_dn, 30);
    lv_obj_set_align(sport_power_dn, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(sport_power_dn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(sport_power_dn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(sport_power_dn, ui_spinbox_dec_cb, LV_EVENT_ALL, sport_speed);
    lv_obj_set_style_radius(sport_power_dn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sport_power_dn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sport_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sport_power_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(sport_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(sport_power_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(sport_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(sport_power_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(sport_power_dn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(sport_power_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * sport_speed_dn = lv_image_create(sport_panel);
    lv_image_set_src(sport_speed_dn, &ui_img_down_arrow_png);
    lv_obj_set_size(sport_speed_dn, 40, 40);
    lv_obj_set_x(sport_speed_dn, -50);
    lv_obj_set_y(sport_speed_dn, 0);
    lv_obj_set_align(sport_speed_dn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(sport_speed_dn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(sport_speed_dn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(sport_speed_dn, ui_spinbox_dec_cb, LV_EVENT_ALL, sport_power);
    lv_obj_set_style_radius(sport_speed_dn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sport_speed_dn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sport_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sport_speed_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(sport_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(sport_speed_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(sport_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(sport_speed_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(sport_speed_dn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(sport_speed_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * sport_speed_up = lv_image_create(sport_panel);
    lv_image_set_src(sport_speed_up, &ui_img_up_arrow_png);
    lv_obj_set_size(sport_speed_up, 40, 40);
    lv_obj_set_align(sport_speed_up, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(sport_speed_up, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(sport_speed_up, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(sport_speed_up, ui_spinbox_inc_cb, LV_EVENT_ALL, sport_power);
    lv_obj_set_style_radius(sport_speed_up, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sport_speed_up, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sport_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sport_speed_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(sport_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(sport_speed_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(sport_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(sport_speed_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(sport_speed_up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(sport_speed_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * race_panel = lv_obj_create(ui_Mode_settings);
    lv_obj_set_height(race_panel, 140);
    lv_obj_set_width(race_panel, lv_pct(100));
    lv_obj_set_align(race_panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(race_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(race_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(race_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(race_panel, lv_color_hex(0xFF2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(race_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(race_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(race_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(race_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(race_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * race_label = lv_label_create(race_panel);
    lv_obj_set_width(race_label, lv_pct(100));
    lv_label_set_text(race_label, "Race Mode Settings");
    lv_obj_set_style_text_font(race_label, &ui_font_Euro15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(race_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(race_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * race_speed = lv_spinbox_create(race_panel);
    lv_obj_set_width(race_speed, 100);
    lv_obj_set_height(race_speed, 42);
    lv_obj_set_align(race_speed, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(race_speed, 0);
    lv_obj_set_y(race_speed, 30);
    lv_obj_remove_flag(race_speed, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                  LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_spinbox_set_digit_format(race_speed, 2, 0);
    lv_spinbox_set_range(race_speed, 0, 9999);
    lv_spinbox_set_cursor_pos(race_speed, 1 - 1);
    lv_obj_set_style_text_color(race_speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(race_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(race_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(race_speed, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(race_speed, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(race_speed, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(race_speed, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_t * race_power = lv_spinbox_create(race_panel);
    lv_obj_set_width(race_power, 100);
    lv_obj_set_height(race_power, 42);
    lv_obj_set_align(race_power, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(race_power, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                  LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_spinbox_set_digit_format(race_power, 4, 0);
    lv_spinbox_set_range(race_power, 100, 9999);
    lv_spinbox_set_cursor_pos(race_power, 3 - 1);
    lv_obj_set_style_text_color(race_power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(race_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(race_power, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(race_power, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(race_power, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(race_power, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(race_power, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_t * race_power_up = lv_image_create(race_panel);
    lv_image_set_src(race_power_up, &ui_img_up_arrow_png);
    lv_obj_set_size(race_power_up, 40, 40);
    lv_obj_set_x(race_power_up, 0);
    lv_obj_set_y(race_power_up, 30);
    lv_obj_set_align(race_power_up, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(race_power_up, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(race_power_up, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(race_power_up, ui_spinbox_inc_cb, LV_EVENT_ALL, race_speed);
    lv_obj_set_style_radius(race_power_up, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(race_power_up, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(race_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(race_power_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(race_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(race_power_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(race_power_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(race_power_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(race_power_up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(race_power_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * race_power_dn = lv_image_create(race_panel);
    lv_image_set_src(race_power_dn, &ui_img_down_arrow_png);
    lv_obj_set_size(race_power_dn, 40, 40);
    lv_obj_set_x(race_power_dn, -50);
    lv_obj_set_y(race_power_dn, 30);
    lv_obj_set_align(race_power_dn, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(race_power_dn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(race_power_dn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(race_power_dn, ui_spinbox_dec_cb, LV_EVENT_ALL, race_speed);
    lv_obj_set_style_radius(race_power_dn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(race_power_dn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(race_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(race_power_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(race_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(race_power_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(race_power_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(race_power_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(race_power_dn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(race_power_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * race_speed_dn = lv_image_create(race_panel);
    lv_image_set_src(race_speed_dn, &ui_img_down_arrow_png);
    lv_obj_set_size(race_speed_dn, 40, 40);
    lv_obj_set_x(race_speed_dn, -50);
    lv_obj_set_y(race_speed_dn, 0);
    lv_obj_set_align(race_speed_dn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(race_speed_dn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(race_speed_dn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(race_speed_dn, ui_spinbox_dec_cb, LV_EVENT_ALL, race_power);
    lv_obj_set_style_radius(race_speed_dn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(race_speed_dn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(race_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(race_speed_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(race_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(race_speed_dn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(race_speed_dn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(race_speed_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(race_speed_dn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(race_speed_dn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * race_speed_up = lv_image_create(race_panel);
    lv_image_set_src(race_speed_up, &ui_img_up_arrow_png);
    lv_obj_set_size(race_speed_up, 40, 40);
    lv_obj_set_align(race_speed_up, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(race_speed_up, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(race_speed_up, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(race_speed_up, ui_spinbox_inc_cb, LV_EVENT_ALL, race_power);
    lv_obj_set_style_radius(race_speed_up, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(race_speed_up, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(race_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(race_speed_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(race_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(race_speed_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(race_speed_up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(race_speed_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(race_speed_up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(race_speed_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Display");
    lv_obj_remove_flag(ui_TabPage3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_back_button = lv_image_create(ui_Settings);
    lv_image_set_src(ui_back_button, &ui_img_88054402);
    lv_obj_set_width(ui_back_button, 40);
    lv_obj_set_height(ui_back_button, 40);
    lv_obj_add_flag(ui_back_button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_back_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_back_button, 10, 10);
    lv_image_set_scale(ui_back_button, 180);
    lv_image_set_inner_align(ui_back_button, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_image_recolor(ui_back_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_back_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_back_button, ui_event_back_button, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    ui_battery_bridge_deinit();
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_Live_battery_info = NULL;
    ui_Voltage = NULL;
    ui_battery_percent = NULL;
    ui_Amps = NULL;
    ui_Battery_Connect_info = NULL;
    ui_Cell_info = NULL;
    ui_TabPage2 = NULL;
    ui_Controller_info = NULL;
    ui_Control_label = NULL;
    ui_data_container = NULL;
    ui_Mode_container = NULL;
    ui_Power_modes = NULL;
    ui_Mode_settings = NULL;
    ui_Eco_Mode = NULL;
    ui_EcoSpeed = NULL;
    ui_EcoPower = NULL;
    ui_TabPage3 = NULL;
    ui_back_button = NULL;

}
